### ISSUE TITLE
Feature Overview: Implementing a score review form 

### ISSUE THREAD

**Issue by elainewangg** [CMU-313/fall22-hw3-team-h3#6]
Description: 
We want to create a new form above the comment section that allows reviewers to update scores for each document. These metrics would ideally be numerical and include metrics such as Fit for the school (1-5), Academic achievement (1-5), and extra-curriculars (1-5). This feature would involve creating a new HTML section or partial with a form, adding new values to the document files, and changing the middleware to connect these values.

Steps:
1. Locate the ‘comments’ partial so we know how comments are currently being displayed on the Teedy page.
2. Make a replica of the comments API above comments except we will call it ‘Score’. 
      - Instead of “string” comments, we will have “int” scores.
      - Every time we enter a score, we want to delete our old score.
3. Make ScoreResource.java that accesses our database 
      - Our database will have a new table that tracks every document with a score, similar to how the comments do
4. Create Javascript functions to support adding, deleting, and editing a score
5. Create a new form that can take in our scores

Division of Work:

Backend Dev: Bonnie
Middleware Dev: Cara, Elaine
Front End: Allen, Eric

**Comment by erohrer5** [comment]
Nice write-up of the feature 👍, Implementation complete!
